# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 771, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.UsernameTextBox = QtWidgets.QTextEdit(self.loginPage)
        self.UsernameTextBox.setGeometry(QtCore.QRect(190, 160, 381, 51))
        self.UsernameTextBox.setObjectName("UsernameTextBox")
        self.ServerIpTextBox = QtWidgets.QTextEdit(self.loginPage)
        self.ServerIpTextBox.setGeometry(QtCore.QRect(190, 260, 381, 51))
        self.ServerIpTextBox.setObjectName("ServerIpTextBox")
        self.PortTextBox = QtWidgets.QTextEdit(self.loginPage)
        self.PortTextBox.setGeometry(QtCore.QRect(300, 360, 151, 41))
        self.PortTextBox.setObjectName("PortTextBox")
        self.label = QtWidgets.QLabel(self.loginPage)
        self.label.setGeometry(QtCore.QRect(340, 130, 71, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.loginPage)
        self.label_2.setGeometry(QtCore.QRect(340, 240, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.loginPage)
        self.label_3.setGeometry(QtCore.QRect(350, 340, 41, 17))
        self.label_3.setObjectName("label_3")
        self.LoginButton = QtWidgets.QPushButton(self.loginPage)
        self.LoginButton.setGeometry(QtCore.QRect(300, 450, 141, 41))
        self.LoginButton.setObjectName("LoginButton")
        self.stackedWidget.addWidget(self.loginPage)
        self.chatPage = QtWidgets.QWidget()
        self.chatPage.setObjectName("chatPage")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.chatPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 161, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ChatSelectLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ChatSelectLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ChatSelectLayout.setContentsMargins(0, 0, 0, 0)
        self.ChatSelectLayout.setObjectName("ChatSelectLayout")
        self.refreshButton = QtWidgets.QPushButton(self.chatPage)
        self.refreshButton.setGeometry(QtCore.QRect(10, 20, 89, 25))
        self.refreshButton.setObjectName("refreshButton")
        self.stackedWidget.addWidget(self.chatPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.LoginButton.clicked.connect(MainWindow.LoginButtonClick) # type: ignore
        self.refreshButton.clicked.connect(MainWindow.RefreshButton) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Server Ip"))
        self.label_3.setText(_translate("MainWindow", "Port"))
        self.LoginButton.setText(_translate("MainWindow", "Login"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
